# use a fix np matrix(128*5) to store the history record
import numpy as np

PREVIOUS_INFO_NP_SIZE = 128
PREVIOUS_INFO_NP_ITEM_SIZE = 7
PREVIOUS_INFO_PADDING = -1000000
PREVIOUS_PADDING_EMPTY = np.full((PREVIOUS_INFO_NP_SIZE, PREVIOUS_INFO_NP_ITEM_SIZE),
                                 PREVIOUS_INFO_PADDING, dtype=np.float32)

COMM_CARD_PADDING = -1
COMM_CARD_NP_SIZE = 4

PLAYER_ACT_PADDING = -1
PLAYER_ACT_NP_LEN = 8
PLAYER_ACT_ITEM_SIZE = 6
