# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: winrate.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwinrate.proto\x12\x02pb\"\x1e\n\x0bRateRequest\x12\x0f\n\x07packets\x18\x01 \x01(\x0c\"\x1c\n\x0cRateResponse\x12\x0c\n\x04rate\x18\x01 \x01(\x02\"#\n\x10\x42\x61tchRateRequest\x12\x0f\n\x07packets\x18\x01 \x03(\x0c\"\"\n\x11\x42\x61tchRateResponse\x12\r\n\x05rates\x18\x01 \x03(\x02\x32\xf0\x01\n\x0eWinRateService\x12,\n\x07GetRate\x12\x0f.pb.RateRequest\x1a\x10.pb.RateResponse\x12;\n\x0c\x42\x61tchGetRate\x12\x14.pb.BatchRateRequest\x1a\x15.pb.BatchRateResponse\x12\x31\n\x0cShortGetRate\x12\x0f.pb.RateRequest\x1a\x10.pb.RateResponse\x12@\n\x11ShortBatchGetRate\x12\x14.pb.BatchRateRequest\x1a\x15.pb.BatchRateResponseB\x1bZ\x19xsyphon.com/holdem/api/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'winrate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031xsyphon.com/holdem/api/pb'
  _globals['_RATEREQUEST']._serialized_start=21
  _globals['_RATEREQUEST']._serialized_end=51
  _globals['_RATERESPONSE']._serialized_start=53
  _globals['_RATERESPONSE']._serialized_end=81
  _globals['_BATCHRATEREQUEST']._serialized_start=83
  _globals['_BATCHRATEREQUEST']._serialized_end=118
  _globals['_BATCHRATERESPONSE']._serialized_start=120
  _globals['_BATCHRATERESPONSE']._serialized_end=154
  _globals['_WINRATESERVICE']._serialized_start=157
  _globals['_WINRATESERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
