# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import core.winrate.winrate_pb2 as winrate__pb2


class WinRateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRate = channel.unary_unary(
                '/pb.WinRateService/GetRate',
                request_serializer=winrate__pb2.RateRequest.SerializeToString,
                response_deserializer=winrate__pb2.RateResponse.FromString,
                )
        self.BatchGetRate = channel.unary_unary(
                '/pb.WinRateService/BatchGetRate',
                request_serializer=winrate__pb2.BatchRateRequest.SerializeToString,
                response_deserializer=winrate__pb2.BatchRateResponse.FromString,
                )
        self.ShortGetRate = channel.unary_unary(
                '/pb.WinRateService/ShortGetRate',
                request_serializer=winrate__pb2.RateRequest.SerializeToString,
                response_deserializer=winrate__pb2.RateResponse.FromString,
                )
        self.ShortBatchGetRate = channel.unary_unary(
                '/pb.WinRateService/ShortBatchGetRate',
                request_serializer=winrate__pb2.BatchRateRequest.SerializeToString,
                response_deserializer=winrate__pb2.BatchRateResponse.FromString,
                )


class WinRateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShortGetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShortBatchGetRate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WinRateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRate,
                    request_deserializer=winrate__pb2.RateRequest.FromString,
                    response_serializer=winrate__pb2.RateResponse.SerializeToString,
            ),
            'BatchGetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetRate,
                    request_deserializer=winrate__pb2.BatchRateRequest.FromString,
                    response_serializer=winrate__pb2.BatchRateResponse.SerializeToString,
            ),
            'ShortGetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.ShortGetRate,
                    request_deserializer=winrate__pb2.RateRequest.FromString,
                    response_serializer=winrate__pb2.RateResponse.SerializeToString,
            ),
            'ShortBatchGetRate': grpc.unary_unary_rpc_method_handler(
                    servicer.ShortBatchGetRate,
                    request_deserializer=winrate__pb2.BatchRateRequest.FromString,
                    response_serializer=winrate__pb2.BatchRateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.WinRateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WinRateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.WinRateService/GetRate',
            winrate__pb2.RateRequest.SerializeToString,
            winrate__pb2.RateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchGetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.WinRateService/BatchGetRate',
            winrate__pb2.BatchRateRequest.SerializeToString,
            winrate__pb2.BatchRateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShortGetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.WinRateService/ShortGetRate',
            winrate__pb2.RateRequest.SerializeToString,
            winrate__pb2.RateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShortBatchGetRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.WinRateService/ShortBatchGetRate',
            winrate__pb2.BatchRateRequest.SerializeToString,
            winrate__pb2.BatchRateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
