from models.agent.manager import register_agent

register_agent(agent_name="ev_v1_aggressive", entry_point="models.agent.winrate.winrate_base_agent:WinrateBaseAgent")
register_agent(agent_name="ev_v2_neutral", entry_point="models.agent.winrate.winrate_base_agent_neutral:WinrateBaseAgentNeutral")
register_agent(agent_name="gto_v1", entry_point="models.agent.winrate.gto_agent_v1:GTOAgentV1")
register_agent(agent_name="gto_v2", entry_point="models.agent.winrate.gto_agent_v2:GTOAgentV2")
register_agent(agent_name="mtt_v1", entry_point="models.agent.winrate.gto_mtt_v1:GTOAgentMTTV1")
register_agent(agent_name="prob_conservative_v1_250909", entry_point="models.agent.winrate.winrate_base_agent_conservative:WinrateBaseAgentConservative")
register_agent(agent_name="random", entry_point="models.agent.simple.random_agent:RandomAgent")
register_agent(agent_name="fold_all_in", entry_point="models.agent.simple.fold_all_in:FoldAllInAgent")
register_agent(agent_name="all_in", entry_point="models.agent.simple.all_in:AllInAgent")
register_agent(agent_name="step_all_in", entry_point="models.agent.simple.step_all_in:StepAllInAgent")
register_agent(agent_name="fold", entry_point="models.agent.simple.fold:FoldAgent")
register_agent(agent_name="step_raise", entry_point="models.agent.simple.step_raise:StepRaiseAgent")
register_agent(agent_name="call", entry_point="models.agent.simple.call:CallAgent")
register_agent(agent_name="winrate_dqn", entry_point="models.agent.winrate.winrate_dqn:WinrateDqnTesting")
register_agent(agent_name="dqn", entry_point="models.agent.dqn.wrap_dqn_agent:WrapDqnAgent")
register_agent(agent_name="proxy", entry_point="models.agent.simple.proxy:ProxyAgent")
register_agent(agent_name="union", entry_point="models.agent.special.union:UnionAgent")
register_agent(agent_name="ppo", entry_point="models.agent.ppo.wrap_ppo_agent:WrapPpoAgent")
register_agent(agent_name="ml_strategy", entry_point="models.agent.winrate.cfr_base_agent:MLBaseAgent")
